#!/bin/bash
while [ 1 ]
do
    osascript -e 'display notification "Rick3d: )A)))#@$)AS)EF" with title "Title."'
	osascript -e 'tell app "Finder" to display dialog "You have been ricked.: )) )) ) ) "' 
	open https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstley
	sleep 5
done

